services: 
  db: 
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DEFAULT_DATABASE_USER}
      - POSTGRES_PASSWORD=${DEFAULT_POSTGRES_PASSWORD}
    volumes:
    - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
