services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${CITY_API_DB_NAME}
      - POSTGRES_USER=${CITY_API_DB_USER}
      - POSTGRES_PASSWORD=${CITY_API_DB_PWD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${CITY_API_DB_USER} -d ${CITY_API_DB_NAME}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build:
      context: ./backend
    restart: unless-stopped
    environment:
      CITY_API_ADDR: ${CITY_API_ADDR}
      CITY_API_PORT: ${CITY_API_PORT}
      CITY_API_DB_URL: ${CITY_API_DB_URL}
      CITY_API_DB_PORT: ${CITY_API_DB_PORT}
      CITY_API_DB_USER: ${CITY_API_DB_USER}
      CITY_API_DB_PWD: ${CITY_API_DB_PWD}
      CITY_API_DB_NAME: ${CITY_API_DB_NAME}
    ports:
      - "2022:2022"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
